version: "3"
services:
    arserver:
        image: alanjohn/argorithm-server:latest
        ports: 
            - 80:80
        volumes:
            - local-uploads:/tmp/argorithm
volumes:
    local-uploads:
        driver: local
