version: "3"
services:
    mongodb:
        image: mongo
        ports: 
            - 27017:27017
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${DB_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
        volumes:
            - mongo-data:/data/db
    redis:
        image: redis
        ports:
            - 6379:6379
        volumes:
            - ./redis.conf:/usr/local/etc/redis/redis.conf
        command: redis-server /usr/local/etc/redis/redis.conf
    arserver:
        image: alanjohn/argorithm-server:latest
        ports: 
            - 80:80
        environment:
            - DATABASE=MONGO
            - AUTH=ENABLED
            - SECRET_KEY=${SECRET_KEY}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_ENDPOINT=mongodb
            - DB_PORT=27017
            - ADMIN_EMAIL=${ADMIN_EMAIL}
            - ADMIN_PASSWORD=${ADMIN_PASSWORD}
            - CACHING=ENABLED
            - REDIS_HOST=redis
            - REDIS_PORT=${REDIS_PORT}
            - REDIS_PASSWORD=${REDIS_PASSWORD}
        volumes:
            - uploads:/tmp/argorithm
        depends_on:
            - mongodb
            - redis
volumes:
    mongo-data:
        driver: local
    uploads:
        driver: local
