{
 "title": "ARgorithm",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": {
    "content": "<img src=\"https://argorithm.el.r.appspot.com/static/Logo_black.svg\">"
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "release_date_info", "legendFormat": "Last release {{last_release}}" },
    { "expr": "python_info", "legendFormat": "python version {{version}}" }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"argorithm.el.r.appspot.com:80\"} / 1024 / 1024 / 1024",
     "legendFormat": "Memory usage"
    }
   ]
  },
  { "title": "Execution details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "execution requests",
   "type": "graph",
   "description": "shows increase in requests",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(execution_requests_total[5m])) by(argorithm_id)",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "average response size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "expr": "avg(execution_response_size_bytes_sum / execution_response_size_bytes_count ) by(argorithm_id)",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "execution time",
   "type": "graph",
   "description": "95th percentile",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(execution_processing_time_milliseconds_bucket[1m])) by (le,argorithm_id))",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "Average time of execution",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(execution_processing_time_milliseconds_sum{status=\"CACHE\"}) / sum(execution_processing_time_milliseconds_count{status=\"CACHE\"})",
     "legendFormat": "Cache execution time"
    },
    {
     "expr": "sum(execution_processing_time_milliseconds_sum{status=\"NORMAL\"}) / sum(execution_processing_time_milliseconds_count{status=\"NORMAL\"})",
     "legendFormat": "Normal execution time"
    }
   ]
  },
  {
   "title": "Percentage cache hits",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(execution_responses_total{status=\"CACHE\"}[5m])) / sum(increase(execution_responses_total[5m])) *100",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Server request stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Response stats",
   "type": "stat",
   "gridPos": { "h": 18, "w": 7, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_responses_total{status_code=~\"2.+\"})/sum(server_responses_total) * 100",
     "legendFormat": "200 responses"
    },
    {
     "expr": "sum(server_responses_total{status_code=~\"4.+\"})/sum(server_responses_total) * 100",
     "legendFormat": "400 responses"
    }
   ]
  },
  {
   "title": "Server requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(server_requests_total[1h])) by (path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Server response status code",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 7, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(server_responses_total[1h])) by(status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  }
 ]
}