apiVersion: v1
kind: Secret
metadata:
    name: app-secret
type: Opaque
data:
    db-username: eW91cnVzZXJuYW1l
    db-password: eW91cnBhc3N3b3Jk
    secret-key: YWRkeW91cnNlY3JldGtleQ==
    admin-password: dGVzdDEyMw==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: db-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  database_url: mongodb-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-configmap
data:
  database: MONGO
  auth: ENABLED
  admin-email: sample@email.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: arserver
  labels:
    app: arserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arserver
  template:
    metadata:
      labels:
        app: arserver
    spec:
      containers:
      - name: arserver
        image: alanjohn/argorithm-server
        ports:
        - containerPort: 80
        env:
        - name: DATABASE
          valueFrom: 
            configMapKeyRef:
              name: app-configmap
              key: database
        - name: AUTH
          valueFrom: 
            configMapKeyRef:
              name: app-configmap
              key: auth
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: db-username
        - name: DB_PASSWORD
          valueFrom: 
            secretKeyRef:
              name: app-secret
              key: db-password
        - name: DB_ENDPOINT
          valueFrom: 
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
        - name: ADMIN_EMAIL
          valueFrom:
            configMapKeyRef:
              name: app-configmap
              key: admin-email
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: admin-password
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: secret-key  
---
apiVersion: v1
kind: Service
metadata:
  name: arserver-service
spec:
  selector:
    app: arserver
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000
