global:
  scrape_interval:     15s
  evaluation_interval: 15s
  external_labels:
      monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server-docker'
    static_configs:
      - targets: ['localhost:9323']

  - job_name: 'argorithm_server'
    static_configs:
      - targets: ['arserver','localhost','argorithm.el.r.appspot.com']

