from ..api import routes 
from ..main import app

@app.route("/")
def hello():
    # This could also be returning an index.html
    return """
    <!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ARgorithm</title>
</head>
<body>
    <style>
        @charset "UTF-8";
        @import url(https://fonts.googleapis.com/css?family=Open + Sans:300, 400, 700);

        body {
        font-family: "Open Sans", sans-serif;
        font-weight: 300;
        line-height: 1.42em;
        color: #ffffff;
        }
        .container th h1 {
        font-weight: bold;
        font-size: 1em;
        text-align: left;
        color: #185875;
        }

        .container td {
        font-weight: normal;
        font-size: 1em;
        -webkit-box-shadow: 0 2px 2px -2px #0e1119;
        -moz-box-shadow: 0 2px 2px -2px #0e1119;
        box-shadow: 0 2px 2px -2px #0e1119;
        }

        .container {
        text-align: center;
        overflow: hidden;
        width: 80%;
        margin: 0 auto;
        display: table;
        padding: 0 0 0 0;
        }

        .container td,
        .container th {
        padding-bottom: 2%;
        padding-top: 2%;
        }

        /* Background-color of the odd rows */
        .container tr:nth-child(odd) {
        background-color: #323c50;
        }

        /* Background-color of the even rows */
        .container tr:nth-child(even) {
        background-color: #2c3446;
        }

        .container th {
        background-color: #1f2739;
        }

        h1 {
            color: #0e1119;
        }


    </style>
    <h1>INDEX</h1>
    <table class="container">
        <tr>
            <th rowspan="4">argorithms</th>
            <td>/argorithms/list</td>
            <td>GET</td>
            <td>returns list of available functions in DB</td>
        </tr>
        <tr>
            <td>/argorithms/insert</td>
            <td>POST</td>
            <td>Inserts argorithm to cloud database</td>
        </tr>
        <tr>
            <td>/argorithms/run</td>
            <td>POST</td>
            <td>returns stateset generated by argorithm on user parameters</td>
        </tr>
        <tr>
            <td>/argorithms/delete</td>
            <td>POST</td>
            <td>deletes argorithm from cloud database</td>
        </tr>
        <tr>
            <th >users</th>
            <td>/users</td>
            <td>GET</td>
            <td>returns list of users in DB</td>
        </tr>
    </table>    
</body>
</html>
    """
