"""start

Revision ID: fb29b273453a
Revises: 
Create Date: 2021-03-05 14:14:15.451950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb29b273453a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programmer',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('black_list', sa.Boolean(), nullable=True),
    sa.Column('join_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_programmer_public_id'), 'programmer', ['public_id'], unique=False)
    op.create_table('user',
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('public_id', sa.String(), nullable=True),
    sa.Column('black_list', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_index(op.f('ix_user_public_id'), 'user', ['public_id'], unique=False)
    op.create_table('argorithm',
    sa.Column('maintainer', sa.String(), nullable=False),
    sa.Column('argorithmID', sa.String(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=False),
    sa.Column('parameters', sa.String(), nullable=True),
    sa.Column('example', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('filedata', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['maintainer'], ['programmer.email'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('argorithmID')
    )
    op.create_table('reports',
    sa.Column('argorithm_id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('bug_type', sa.Enum('User', 'System', 'Alert', name='reporttype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['argorithm_id'], ['argorithm.argorithmID'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('report_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_table('argorithm')
    op.drop_index(op.f('ix_user_public_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_programmer_public_id'), table_name='programmer')
    op.drop_table('programmer')
    # ### end Alembic commands ###
