{
 "title": "ARgorithm",
 "description": "Dashboard specifically designed for ARgorithm Server",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "2XX status code responses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_responses_total{status_code=~\"2..\"}[1h])) / sum(increase(server_responses_total[1h])) * 100"
    }
   ]
  },
  {
   "title": "4XX response status codes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_responses_total{status_code=~\"4..\"}[1h])) / sum(increase(server_responses_total[1h])) * 100"
    }
   ]
  },
  {
   "title": "5XX response status codes",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(server_responses_total{status_code=~\"5..\"}[1h])) / sum(increase(server_responses_total[1h])) * 100"
    }
   ]
  },
  {
   "title": "Time taken by Server Requests",
   "type": "graph",
   "description": "time taken by 95% of requests for a given path in last 5 mins",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s", "label": "Time taken (p95)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(server_requests_processing_time_seconds_bucket[5m])) by (le,path))"
    }
   ]
  },
  {
   "title": "Requests per hour",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(server_requests_total[1h])) by(path)",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "ARgorithm Execution Requests per hour",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(execution_requests_total[1h])) by(argorithm_id)",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "% states returned from cache",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(increase(execution_responses_total{status=\"CACHE\"}[5m])) / sum(increase(execution_responses_total[5m])) * 100"
    }
   ]
  },
  {
   "title": "Execution with user defined parameters",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(increase(execution_requests_total{parameters=\"PROVIDED\"}[1m])) / sum(increase(execution_requests_total[1m])) * 100"
    }
   ]
  },
  {
   "title": "Time taken by exectution requests p50",
   "type": "graph",
   "description": "median of all request duration by argorithm ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "median time taken" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(execution_processing_time_milliseconds_bucket[5m])) by (le,argorithm_id))",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "Execution stateset size p50",
   "type": "graph",
   "description": "Median stateset size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "yaxes": [
    { "format": "kbytes", "label": "Response packet size (median)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(execution_response_size_bytes_bucket[5m])) by (le,argorithm_id)) ",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "Time taken by exectution requests p95",
   "type": "graph",
   "description": "95th percentile of all request duration by argorithm ID",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms", "label": "Time taken p95" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(execution_processing_time_milliseconds_bucket[5m])) by (le,argorithm_id))",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "Execution stateset size p95",
   "type": "graph",
   "description": "95th percentile stateset size",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "yaxes": [
    { "format": "kbytes", "label": "Response packet size (p95)" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(execution_response_size_bytes_bucket[5m])) by (le,argorithm_id)) ",
     "legendFormat": "{{argorithm_id}}"
    }
   ]
  },
  {
   "title": "Database command success rate",
   "type": "stat",
   "description": "The % of database functions successfully executed in last 15 mins",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(database_event_finished_total{status=\"success\"}[5m])) by (command) / sum(rate(database_event_finished_total[5m])) by (command) * 100",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Time taken for database operations",
   "type": "graph",
   "description": "median time taken command wise over the last 5 mins",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(database_event_time_bucket[5m])) by (le,command))",
     "legendFormat": "{{command}}"
    }
   ]
  }
 ]
}